FROM node:18-alpine as builder

ENV NODE_ENV build

USER node
WORKDIR /home/node

COPY --chown=node:node . .
RUN npm ci


RUN npm run build \
    && npm prune --production

# ---

FROM node:18-alpine

ARG DATABASE_URL
ARG PORT
ARG JWT_ACCESS_TOKEN_SECRET
ARG JWT_ACCESS_TOKEN_DURATION
ARG EMAIL_CONFIRMATION_ACCOUNT_URL
ARG UNSUBSCRIBE_URL
ARG EMAIL_SERVICE
ARG EMAIL_USER
ARG GENERATED_EMAIL_PASSWORD
ARG CGV_FILE_PATH
ARG AWS_REGION
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_PUBLIC_BUCKET_NAME
ARG STRIPE_SECRET_KEY
ARG STRIPE_CURRENCY

ENV \
DATABASE_URL=${DATABASE_URL} \
PORT=${PORT} \
JWT_ACCESS_TOKEN_SECRET=${JWT_ACCESS_TOKEN_SECRET} \
JWT_ACCESS_TOKEN_DURATION=${JWT_ACCESS_TOKEN_DURATION} \
EMAIL_CONFIRMATION_ACCOUNT_URL=${EMAIL_CONFIRMATION_ACCOUNT_URL}\
UNSUBSCRIBE_URL=${UNSUBSCRIBE_URL}\
EMAIL_SERVICE=${EMAIL_SERVICE}\
EMAIL_USER=${EMAIL_USER}\
GENERATED_EMAIL_PASSWORD=${GENERATED_EMAIL_PASSWORD}\
CGV_FILE_PATH=${CGV_FILE_PATH}\
AWS_REGION=${AWS_REGION}\
AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}\
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}\
AWS_PUBLIC_BUCKET_NAME=${AWS_PUBLIC_BUCKET_NAME}\
STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}\
STRIPE_CURRENCY=${STRIPE_CURRENCY}

USER node
WORKDIR /home/node

COPY --from=builder --chown=node:node /home/node/package*.json ./
COPY --from=builder --chown=node:node /home/node/node_modules/ ./node_modules/
COPY --from=builder --chown=node:node /home/node/dist/ ./dist/

EXPOSE 3000

CMD ["node", "dist/main.js"]
